script:
  - "istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec"

notifications:
  email:
    - lebretr@gmail.com

language: node_js

node_js:
  - "0.10"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

addons:
  code_climate:
    repo_token: 11d1bd7cef26b41b6b0d48f8d3da6b2c466e22229e794226ef6cc8a77cdb297e

after_script:
  - cat ./coverage/lcov.info | codeclimate
